language: java

notifications:
  email: false

addons:
  sonarcloud:
    organization: "piercirocaliandro"

  token:
    secure: "XaVze8yCh8hRIskUGQP0+MTTQLP1+buCd67uEcZ7NzGtBzkcw8y4Ta+ZN/bxVYCwSV+DbeX/1f3Q3LUr5SpZmLj3QNaK/cjfAFJrMzFwIjn30gwkh87vC4yFRq2m6ZaBBXSvltoXsP3OVj+1mqLiixMmYObUe67ByWKO1D4btQGFsiEY94Rit2PuWvUdfetaZWNFEVMvd8PYvaZlJRSb/5I48X0xZYuugKie/7ElCcA3NcHNSyg/wJN/FcZUyjdevfCWI+uKgxjAZh20mix8LWz2mfjN9Dss2O/qoD8CAuoJ7+nyaRLBuBT8yuuPttJJW7VzYJSWw/0XfAWDri8pjTWyrhOKcPRcfFJya+sGyFdXcfAgTkKjEqHffoqwsh2WZWJDnGTz/+b7AYNttDFVF6St4iI+TP+ky1hcVoweQZ77ED8aAL32+9u1okpiv5AmBa3anYjUKoMb3QOXkzHdC7cchuj/TxNgsuMDc9XuxDBXi6ghkyg5rbNmBp3YnuV2iPOSCW5HlAPWlOug0FYgskC/D89z5YuVeHRPaKxLE+goscG64gNPKJVOhCC7PkiSeWd2G3y3AbYfi69lQC78owq799HuFxWrDx/IYrJEvLg385TiIjzlMj1O4SUbpnbqFOOv/GoFuaA6T1eVyqJMPlLbTefkCOoxgdnQZidEXAY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=piercirocaliandro_isw2-deliverable1
