language: java
notifications:
  email: false
addons:
  sonarcloud:
    organization: "piercirocaliandro"
    token:
      secure: "Lq6RfOZSs755SPCTVJjmp7vrc4JZOwIgZEZrw1sHBCWUAXQizNdexsXo4adl9kdt5jYwEEcRqVZ++idW5X38oocca+gzZdfXAwrlMgIz3nuP2cahg+g19PMxh+q8k07E/RbanGQKqziX6xDNzTjYLlIJVFlDnhKlEYriJ/3q1iZ2eE9JLbS+38KFnOB4y+8eGqQj6bBk/hn8i3iTH+9+AwPh9zn5G/TKYhe2Zs1T63E4uc+KvysEPaykK3Rs3bzHDvcAle2aWnB7eZzRnOG048qRZLpIE3b5ex6noJO8T0zAagvXEpV+grYQiUrDJNZeyK84Xw8zdCQyqFEUvxIvbwizPZWxtFq38ieTs6/8kvObHsPwBBcxxWMTPOaXrjgqxfCh3VvXiznb2IivZ1dGzhPufylVWmnQjPoeFFxQIF/ke6Sl/sqcFsa6PjH3keA0auIHKC2Mhi2Xuw9XB5qPvxaU8Rq13HE015CsmHk0stD0ms7Ri5dYfWBnxziHVkI2ybJ/btCS1lBqjWcEg3LcqxfePbakw15quaTw/bNPvi1HPTfApherlMF9vAc8mQEvu6dpEzGphOo1uGnYW2fbkVzgdNXKAJdXjm+ABUtxuA62EQKqHvWttmZBuHeDKG3MbZ4wkbOadvwmr8vRuR51Dlx5vspmm1T8inXnLJ8Coxk="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
env:
  global:
    secure: Lq6RfOZSs755SPCTVJjmp7vrc4JZOwIgZEZrw1sHBCWUAXQizNdexsXo4adl9kdt5jYwEEcRqVZ++idW5X38oocca+gzZdfXAwrlMgIz3nuP2cahg+g19PMxh+q8k07E/RbanGQKqziX6xDNzTjYLlIJVFlDnhKlEYriJ/3q1iZ2eE9JLbS+38KFnOB4y+8eGqQj6bBk/hn8i3iTH+9+AwPh9zn5G/TKYhe2Zs1T63E4uc+KvysEPaykK3Rs3bzHDvcAle2aWnB7eZzRnOG048qRZLpIE3b5ex6noJO8T0zAagvXEpV+grYQiUrDJNZeyK84Xw8zdCQyqFEUvxIvbwizPZWxtFq38ieTs6/8kvObHsPwBBcxxWMTPOaXrjgqxfCh3VvXiznb2IivZ1dGzhPufylVWmnQjPoeFFxQIF/ke6Sl/sqcFsa6PjH3keA0auIHKC2Mhi2Xuw9XB5qPvxaU8Rq13HE015CsmHk0stD0ms7Ri5dYfWBnxziHVkI2ybJ/btCS1lBqjWcEg3LcqxfePbakw15quaTw/bNPvi1HPTfApherlMF9vAc8mQEvu6dpEzGphOo1uGnYW2fbkVzgdNXKAJdXjm+ABUtxuA62EQKqHvWttmZBuHeDKG3MbZ4wkbOadvwmr8vRuR51Dlx5vspmm1T8inXnLJ8Coxk=
